# Write your MySQL query statement below
WITH Q AS (SELECT * FROM PRODUCTS WHERE CHANGE_DATE<='2019-08-16')

SELECT P5.PRODUCT_ID, CASE 
WHEN P5.price is NULL THEN 10 
ELSE P5.price 
END AS price  
FROM (SELECT P3.PRODUCT_ID,P4.NEW_PRICE AS 'price'  FROM (SELECT PRODUCT_ID FROM PRODUCTS GROUP BY product_id ) P3 LEFT JOIN (SELECT P1.product_id,P1.new_price FROM PRODUCTS P1
JOIN  (SELECT PRODUCT_ID , MAX(CHANGE_DATE) as change_date FROM Q
GROUP BY PRODUCT_ID) P2
ON P1.PRODUCT_ID=P2.PRODUCT_ID AND P1.CHANGE_DATE =P2.CHANGE_DATE) P4
ON P3.PRODUCT_ID=P4.PRODUCT_ID) P5